### ISSUE TITLE
TypeError: Cannot set property 'exports' of undefined

### ISSUE THREAD

**Issue by TheDigitalCat** [crhossen/photo-booth#1]
bash-3.2$ node ./bin/www

/Users/neznae4ko/_crhossen_photo-booth/photo-booth/routes/index.js:17
module.exports = router;
               ^
TypeError: Cannot set property 'exports' of undefined
    at Object.<anonymous> (/Users/neznae4ko/_crhossen_photo-booth/photo-booth/routes/index.js:17:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/neznae4ko/_crhossen_photo-booth/photo-booth/app.js:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
bash-3.2$

**Comment by TheDigitalCat** [comment]
photo-booth/routes/index.js

});  not }).
